DROP TABLE IF EXISTS TBL_EMPOLYEE

CREATE TABLE TBL_EMPLOYEE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARHCAR(255) NOT NULL,
    last_name VARHCAR(255) NOT NULL,
    email VARHCAR(255) DEFAULT NULL,

);
